# Generated by Django 3.2.5 on 2021-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('1', 'ACCEPTED'), ('2', 'REJECTED'), ('3', 'PENDING')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='file',
            name='status_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
