# Generated by Django 3.2.5 on 2021-09-05 10:35

import crwproject.xml_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='updated_file',
            field=models.FileField(blank=True, null=True, upload_to=crwproject.xml_app.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml']), crwproject.xml_app.models.max_file_size]),
        ),
    ]
