# Generated by Django 3.2.5 on 2021-09-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xml_app', '0002_file_updated_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_content',
        ),
    ]
